### ISSUE TITLE
Simple way to trim a video

### ISSUE THREAD

**Issue by Soremwar** [oddity-ai/oddity-video#3]
Coming here after messing with `ffmpeg_next` directly. I'm surprised that there wasn't a library for high level abstractions earlier

So anyways, I'm looking for a way to seek a fragment of a video and output it to a file (roughly `ffmpeg -i input.mp4 -ss 00:00:00 -t 00:10:00 -c:v copy -c:a copy output1.mp4` with the CLI)

IS there a way to accomplish this without iterating through the whole video?

**Comment by gerwin3** [comment]
This library is built on `ffmpeg_next` actually! There is a way to do it using `video-rs` (and would also work for `ffmpeg_next`). You can use the reader (https://docs.rs/video-rs/0.1.7/video_rs/struct.Reader.html) to read packets and write them using a writer without any encoding/decoding. That is roughly similar to what ffmpeg would do if you use the command above. You can use the PTS (https://docs.rs/video-rs/0.1.7/video_rs/struct.Packet.html#method.pts) to figure out when to start and stop trimming.

This approach does still require iterating over the packets, and there is no high-level API to abstract that away. It is a bit out of the scope of this library. Note that going through all the packets in the stream is also what ffmpeg does when you run the command above.

Good luck!

**Comment by Soremwar** [comment]
The Write trait methods seem to be private though

**Comment by gerwin3** [comment]
Sorry, that should be muxer, not writer.

**Comment by Soremwar** [comment]
Got it, however using FileWriter it seems I can't write a file when not starting from the beginning of the file (trimming from 30s to 50s yields a 50s video with only 20s of content instead of a 20s one)

Changing packet pts just panics of course

**Comment by gerwin3** [comment]
Changing packet pts should do the trick here. Does libavformat panic? Maybe you also need to update dts? Also, I think you must start with a keyframe (you can check packet flags with `AV_PKT_FLAG_KEY`). You probably need to find a keyframe packet that is closest to the intended start of your trim. You'll notice that when using ffmpeg to trim (without re-encoding), the trim will not start at the exact specified point for the same reason.

**Comment by Soremwar** [comment]
Using the following code

```rs
loop {
  match reader.read(reader_stream) {
    Ok(mut packet) => {
      let position: Duration = packet.pts().into();

      if position < start {
        continue;
      } else if position <= end {
        let new_position = position - start; // Start is another duration
        packet.set_pts(&new_position.into());

        if muxer.mux(packet).is_err() {
          return Err("Could not write fragment".into());
        }
      } else {
        if muxer.finish().is_err() {
          return Err("Could not write end fragment".into());
        }
        break;
      }
    }
    // If file has ended
    Err(ReadExhausted) => {
      if muxer.finish().is_err() {
        return Err("Could not write end fragment".into());
      }
      break;
    }
    _ => {
      return Err("Could not read from source".into());
    }
  };
}
```

I get
```log
[mp4 @ 0x560fba7045c0] pts (14400) < dts (2696400) in stream 0
Error: "Could not write fragment"
````

**Comment by gerwin3** [comment]
You should also change the DTS! The correct way to do this would be to calculate the offset (PTS of first fragment) at the beginning, then subtract that from the DTS for every packet i.e. `packet.set_dts(packet.dts() - start_pts)`. You could maybe also get away with just doing `packet.set_dts(new_position)`.
